import turtle
turtle.color("orange")
turtle.width(5)
turtle.bgcolor("white")
for i in range (6):
    turtle.color("pink")
    turtle.forward(100)
    turtle.left(90)
    turtle.color("black")
    turtle.forward(100)
    turtle.right(90)
    turtle.color("pink")
    turtle.forward(40)
    turtle.right(90)
    turtle.color("black")
    turtle.forward(100)
    turtle.left(30)
    turtle.color("yellow")
    turtle.forward(100)
turtle.exitonclick()